version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./html:/var/www/html/
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: clear_nginx